// This file is automatically generated. DO NOT EDIT.

package testkeys

import (
	"crypto/ecdsa"

    _ "embed"
)

//go:embed keys/ecdsa_p256.key
var ecP256PrivateKeyPEM []byte

var ecP256PublicKeyPEM []byte
var ecP256PrivateKey *ecdsa.PrivateKey

//nolint:gochecknoinits // generated code
func init() {
    ecP256PrivateKey = MustParseECPrivateKey(ecP256PrivateKeyPEM)
    ecP256PublicKeyPEM = MustMarshalPublicKey(&ecP256PrivateKey.PublicKey)
}

// GetECP256PrivateKey returns a known ECDSA-P256 private key.
func GetECP256PrivateKey() *ecdsa.PrivateKey {
    return ecP256PrivateKey
}

// GetECP256PublicKey returns a known ECDSA-P256 public key.
func GetECP256PublicKey() *ecdsa.PublicKey {
    return &ecP256PrivateKey.PublicKey
}

// GetECP256PublicKeyPEM returns a known ECP256 private key in PEM format.
func GetECP256PublicKeyPEM() []byte {
    return ecP256PublicKeyPEM
}
