// This file is automatically generated. DO NOT EDIT.

package testkeys_test

import (
	"testing"

	"github.com/tprasadtp/cryptokms/internal/cryptoutils"
	"github.com/tprasadtp/cryptokms/internal/testkeys"
)


func Test_Get_ECP521(t *testing.T) {
	// Ensure Key is of right type.
	priv := testkeys.GetECP521PrivateKey()
	if priv.Curve.Params().Name != "P-521" {
		t.Errorf("Invalid curve, expected=P-521, but got=%s", priv.Curve.Params().Name)
	}

    // Ensure Public key is returned which corresponds to Private key
    if !priv.PublicKey.Equal(testkeys.GetECP521PublicKey()) {
        t.Errorf("GetECP521PrivateKey/PublicKey != GetECP521PublicKey")
    }

    // Ensure GetECP521PublicKey returns same key as GetECP521PublicKeyPEM
    pubFromPEM := cryptoutils.MustParseECPublicKey(testkeys.GetECP521PublicKeyPEM())
    if ! pubFromPEM.Equal(testkeys.GetECP521PublicKey()) {
        t.Errorf("parse(GetECP521PublicKeyPEM) != GetECP521PublicKey")
    }
}
