// This file is automatically generated. DO NOT EDIT.

package testkeys_test

import (
	"testing"

    "github.com/tprasadtp/cryptokms/internal/testkeys"
)


func Test_Get_ECP{{.Size}}(t *testing.T) {
	// Ensure Key is of right type.
	priv := testkeys.GetECP{{.Size}}PrivateKey()
	if priv.Curve.Params().Name != "P-{{.Size}}" {
		t.Errorf("Invalid curve, expected=P-{{.Size}}, but got=%s", priv.Curve.Params().Name)
	}

    // Ensure Public key is returned which corresponds to Private key
    if !priv.PublicKey.Equal(testkeys.GetECP{{.Size}}PublicKey()) {
        t.Errorf("GetECP{{.Size}}PrivateKey/PublicKey != GetECP{{.Size}}PublicKey")
    }

    // Ensure GetECP{{.Size}}PublicKey returns same key as GetECP{{.Size}}PublicKeyPEM
    pubFromPEM := testkeys.MustParseECPublicKey(testkeys.GetECP{{.Size}}PublicKeyPEM())
    if ! pubFromPEM.Equal(testkeys.GetECP{{.Size}}PublicKey()) {
        t.Errorf("parse(GetECP{{.Size}}PublicKeyPEM) != GetECP{{.Size}}PublicKey")
    }
}
