// This file is automatically generated. DO NOT EDIT.

package testkeys_test

import (
	"testing"

	"github.com/tprasadtp/cryptokms/internal/cryptoutils"
	"github.com/tprasadtp/cryptokms/internal/testkeys"
)


func Test_Get_ECP384(t *testing.T) {
	// Ensure Key is of right type.
	priv := testkeys.GetECP384PrivateKey()
	if priv.Curve.Params().Name != "P-384" {
		t.Errorf("Invalid curve, expected=P-384, but got=%s", priv.Curve.Params().Name)
	}

    // Ensure Public key is returned which corresponds to Private key
    if !priv.PublicKey.Equal(testkeys.GetECP384PublicKey()) {
        t.Errorf("GetECP384PrivateKey/PublicKey != GetECP384PublicKey")
    }

    // Ensure GetECP384PublicKey returns same key as GetECP384PublicKeyPEM
    pubFromPEM := cryptoutils.MustParseECPublicKey(testkeys.GetECP384PublicKeyPEM())
    if ! pubFromPEM.Equal(testkeys.GetECP384PublicKey()) {
        t.Errorf("parse(GetECP384PublicKeyPEM) != GetECP384PublicKey")
    }
}
