// This file is automatically generated. DO NOT EDIT.

package testkeys

import (
	"crypto/ecdsa"

    _ "embed"

    "github.com/tprasadtp/cryptokms/internal/cryptoutils"
)

//go:embed keys/ecdsa_p384.key
var ecP384PrivateKeyPEM []byte

var ecP384PublicKeyPEM []byte
var ecP384PrivateKey *ecdsa.PrivateKey

//nolint:gochecknoinits // generated code
func init() {
    ecP384PrivateKey = cryptoutils.MustParseECPrivateKey(ecP384PrivateKeyPEM)
    ecP384PublicKeyPEM = cryptoutils.MustMarshalPublicKey(&ecP384PrivateKey.PublicKey)
}

// GetECP384PrivateKey returns a known ECDSA-P384 private key.
func GetECP384PrivateKey() *ecdsa.PrivateKey {
    return ecP384PrivateKey
}

// GetECP384PublicKey returns a known ECDSA-P384 public key.
func GetECP384PublicKey() *ecdsa.PublicKey {
    return &ecP384PrivateKey.PublicKey
}

// GetECP384PublicKeyPEM returns a known ECP384 private key in PEM format.
func GetECP384PublicKeyPEM() []byte {
    return ecP384PublicKeyPEM
}
