// This file is automatically generated. DO NOT EDIT.

package testkeys

import (
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
)

// Keys are generated on package import
// These keys must only be used for testing.
var (
	rsa2048PrivateKey *rsa.PrivateKey
	rsa3072PrivateKey *rsa.PrivateKey
	rsa4096PrivateKey *rsa.PrivateKey

	ecdsaP256PrivateKey *ecdsa.PrivateKey
	ecdsaP384PrivateKey *ecdsa.PrivateKey
	ecdsaP521PrivateKey *ecdsa.PrivateKey

	ed25519PrivateKey ed25519.PrivateKey
	ed25519PublicKey  ed25519.PublicKey
)

// Generate Keys.
//
//nolint:gochecknoinits // seed test keys
func init() {

	rsa2048PrivateKey, _ = rsa.GenerateKey(rand.Reader, 2048)
	rsa3072PrivateKey, _ = rsa.GenerateKey(rand.Reader, 2048)
	rsa4096PrivateKey, _ = rsa.GenerateKey(rand.Reader, 2048)

	ecdsaP256PrivateKey, _ = ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	ecdsaP384PrivateKey, _ = ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
	ecdsaP521PrivateKey, _ = ecdsa.GenerateKey(elliptic.P521(), rand.Reader)

	ed25519PublicKey, ed25519PrivateKey, _ = ed25519.GenerateKey(rand.Reader)
}

// Get2048PrivateKey returns a RSA 2048 bit private key.
// This private key is unique per execution of the binary and corresponds
// to public key returned by [GetRSA2048PublicKey].
func GetRSA2048PrivateKey() *rsa.PrivateKey {
	return rsa2048PrivateKey
}

// Get2048PublicKey returns a RSA 2048 bit public key.
// This pub key is unique per execution of the binary and corresponds
// to private key returned by [GetRSA2048PrivateKey].
func GetRSA2048PublicKey() *rsa.PublicKey {
	return &rsa2048PrivateKey.PublicKey
}

// GetRSA2048PublicKey returns RSA 2048 bit public key in PEM format.
// This pub key is unique per execution of the binary and corresponds
// to private key returned by [GetRSA2048PrivateKey].
func GetRSA2048PublicKeyPEM() []byte {
	return MustMarshalPublicKey(&rsa2048PrivateKey.PublicKey)
}

// Get3072PrivateKey returns a RSA 3072 bit private key.
// This private key is unique per execution of the binary and corresponds
// to public key returned by [GetRSA3072PublicKey].
func GetRSA3072PrivateKey() *rsa.PrivateKey {
	return rsa3072PrivateKey
}

// Get3072PublicKey returns a RSA 3072 bit public key.
// This pub key is unique per execution of the binary and corresponds
// to private key returned by [GetRSA3072PrivateKey].
func GetRSA3072PublicKey() *rsa.PublicKey {
	return &rsa3072PrivateKey.PublicKey
}

// GetRSA3072PublicKey returns RSA 3072 bit public key in PEM format.
// This pub key is unique per execution of the binary and corresponds
// to private key returned by [GetRSA3072PrivateKey].
func GetRSA3072PublicKeyPEM() []byte {
	return MustMarshalPublicKey(&rsa3072PrivateKey.PublicKey)
}

// Get4096PrivateKey returns a RSA 4096 bit private key.
// This private key is unique per execution of the binary and corresponds
// to public key returned by [GetRSA4096PublicKey].
func GetRSA4096PrivateKey() *rsa.PrivateKey {
	return rsa4096PrivateKey
}

// Get4096PublicKey returns a RSA 4096 bit public key.
// This pub key is unique per execution of the binary and corresponds
// to private key returned by [GetRSA4096PrivateKey].
func GetRSA4096PublicKey() *rsa.PublicKey {
	return &rsa4096PrivateKey.PublicKey
}

// GetRSA4096PublicKey returns RSA 4096 bit public key in PEM format.
// This pub key is unique per execution of the binary and corresponds
// to private key returned by [GetRSA4096PrivateKey].
func GetRSA4096PublicKeyPEM() []byte {
	return MustMarshalPublicKey(&rsa4096PrivateKey.PublicKey)
}

// GetECP256PrivateKey returns a EC P-256 bit private key.
// This private key is unique per execution of the binary and corresponds
// to public key returned by [GetECP256PublicKey].
func GetECP256PrivateKey() *ecdsa.PrivateKey {
	return ecdsaP256PrivateKey
}

// GetECP256PublicKey returns a EC P-256 bit public key.
// This pub key is unique per execution of the binary and corresponds
// to private key returned by [GetECP256PrivateKey].
func GetECP256PublicKey() *ecdsa.PublicKey {
	return &ecdsaP256PrivateKey.PublicKey
}

// GetECP256PublicKey returns EC P-256 public key in PEM format.
// This pub key is unique per execution of the binary and corresponds
// to private key returned by [GetECP256PrivateKey].
func GetECP256PublicKeyPEM() []byte {
	return MustMarshalPublicKey(&ecdsaP256PrivateKey.PublicKey)
}

// GetECP384PrivateKey returns a EC P-384 bit private key.
// This private key is unique per execution of the binary and corresponds
// to public key returned by [GetECP384PublicKey].
func GetECP384PrivateKey() *ecdsa.PrivateKey {
	return ecdsaP384PrivateKey
}

// GetECP384PublicKey returns a EC P-384 bit public key.
// This pub key is unique per execution of the binary and corresponds
// to private key returned by [GetECP384PrivateKey].
func GetECP384PublicKey() *ecdsa.PublicKey {
	return &ecdsaP384PrivateKey.PublicKey
}

// GetECP384PublicKey returns EC P-384 public key in PEM format.
// This pub key is unique per execution of the binary and corresponds
// to private key returned by [GetECP384PrivateKey].
func GetECP384PublicKeyPEM() []byte {
	return MustMarshalPublicKey(&ecdsaP384PrivateKey.PublicKey)
}

// GetECP521PrivateKey returns a EC P-521 bit private key.
// This private key is unique per execution of the binary and corresponds
// to public key returned by [GetECP521PublicKey].
func GetECP521PrivateKey() *ecdsa.PrivateKey {
	return ecdsaP521PrivateKey
}

// GetECP521PublicKey returns a EC P-521 bit public key.
// This pub key is unique per execution of the binary and corresponds
// to private key returned by [GetECP521PrivateKey].
func GetECP521PublicKey() *ecdsa.PublicKey {
	return &ecdsaP521PrivateKey.PublicKey
}

// GetECP521PublicKey returns EC P-521 public key in PEM format.
// This pub key is unique per execution of the binary and corresponds
// to private key returned by [GetECP521PrivateKey].
func GetECP521PublicKeyPEM() []byte {
	return MustMarshalPublicKey(&ecdsaP521PrivateKey.PublicKey)
}

// GetED25519PrivateKey returns ED-25519 private key.
// This private key is unique per execution of the binary
// and corresponds to public key returned by [GetED25519PublicKey].
func GetED25519PrivateKey() ed25519.PrivateKey {
	return ed25519PrivateKey
}

// GetED25519PublicKey returns ED-25519 public key.
// This public key is unique per execution of the binary
// and corresponds to private key returned by [GetED25519PrivateKey].
func GetED25519PublicKey() ed25519.PublicKey {
	return ed25519PublicKey
}

// GetED25519PublicKeyPEM returns ED-25519 public key in PEM format.
func GetED25519PublicKeyPEM() []byte {
	return MustMarshalPublicKey(ed25519PublicKey)
}
