// This file is automatically generated. DO NOT EDIT.

package testkeys_test

import (
	"testing"

	"github.com/tprasadtp/cryptokms/internal/cryptoutils"
	"github.com/tprasadtp/cryptokms/internal/testkeys"
)


func Test_Get_RSA{{.Size}}(t *testing.T) {
    // Ensure Public key is returned which corresponds to Private key
    priv := testkeys.GetRSA{{.Size}}PrivateKey()
    if !priv.PublicKey.Equal(testkeys.GetRSA{{.Size}}PublicKey()) {
        t.Errorf("GetRSA{{.Size}}PrivateKey.PublicKey != GetRSA{{.Size}}PrivateKey")
    }

    // Ensure GetRSA{{.Size}}PublicKey returns same key as GetRSA{{.Size}}PublicKeyPEM
    pubFromPEM := cryptoutils.MustParseRSAPublicKey(testkeys.GetRSA{{.Size}}PublicKeyPEM())
	if !pubFromPEM.Equal(testkeys.GetRSA{{.Size}}PublicKey()) {
		t.Errorf("parse(GetRSA{{.Size}}PrivateKeyPEM) != GetRSA{{.Size}}PrivateKey.Public")
	}
}
