// This file is automatically generated. DO NOT EDIT.

package testkeys_test

import (
	"testing"

	"github.com/tprasadtp/cryptokms/internal/cryptoutils"
	"github.com/tprasadtp/cryptokms/internal/testkeys"
)


func Test_Get_RSA2048(t *testing.T) {
    // Ensure Public key is returned which corresponds to Private key
    priv := testkeys.GetRSA2048PrivateKey()
    if !priv.PublicKey.Equal(testkeys.GetRSA2048PublicKey()) {
        t.Errorf("GetRSA2048PrivateKey.PublicKey != GetRSA2048PrivateKey")
    }

    // Ensure GetRSA2048PublicKey returns same key as GetRSA2048PublicKeyPEM
    pubFromPEM := cryptoutils.MustParseRSAPublicKey(testkeys.GetRSA2048PublicKeyPEM())
	if !pubFromPEM.Equal(testkeys.GetRSA2048PublicKey()) {
		t.Errorf("parse(GetRSA2048PrivateKeyPEM) != GetRSA2048PrivateKey.Public")
	}
}
