// This file is automatically generated. DO NOT EDIT.

package testkeys_test

import (
	"testing"

	"github.com/tprasadtp/cryptokms/internal/testkeys"
)


func Test_Get_RSA4096(t *testing.T) {
    // Ensure Public key is returned which corresponds to Private key
    priv := testkeys.GetRSA4096PrivateKey()
    if !priv.PublicKey.Equal(testkeys.GetRSA4096PublicKey()) {
        t.Errorf("GetRSA4096PrivateKey.PublicKey != GetRSA4096PrivateKey")
    }

    // Ensure GetRSA4096PublicKey returns same key as GetRSA4096PublicKeyPEM
    pubFromPEM := testkeys.MustParseRSAPublicKey(testkeys.GetRSA4096PublicKeyPEM())
	if !pubFromPEM.Equal(testkeys.GetRSA4096PublicKey()) {
		t.Errorf("parse(GetRSA4096PrivateKeyPEM) != GetRSA4096PrivateKey.Public")
	}
}
