// This file is automatically generated. DO NOT EDIT.

package testkeys

import (
	"crypto/rsa"
    _ "embed"
)

//go:embed keys/rsa_4096.key
var rsa4096PrivateKeyPEM []byte

var rsa4096PublicKeyPEM []byte
var rsa4096PrivateKey *rsa.PrivateKey

//nolint:gochecknoinits // generated code
func init() {
    rsa4096PrivateKey = MustParseRSAPrivateKey(rsa4096PrivateKeyPEM)
	rsa4096PublicKeyPEM = MustMarshalPublicKey(&rsa4096PrivateKey.PublicKey)
}

// GetRSA4096PrivateKey returns a known RSA4096 private key.
func GetRSA4096PrivateKey() *rsa.PrivateKey {
    return rsa4096PrivateKey
}

// GetRSA4096PublicKey returns a known RSA4096 private key.
func GetRSA4096PublicKey() *rsa.PublicKey {
    return &rsa4096PrivateKey.PublicKey
}

// GetRSA4096PublicKeyPEM returns a known RSA4096 public key in PEM format.
func GetRSA4096PublicKeyPEM() []byte {
    return rsa4096PublicKeyPEM
}
