// This file is automatically generated. DO NOT EDIT.

package testkeys

import (
	"crypto/rsa"
    _ "embed"
)

//go:embed keys/rsa_3072.key
var rsa3072PrivateKeyPEM []byte

var rsa3072PublicKeyPEM []byte
var rsa3072PrivateKey *rsa.PrivateKey

//nolint:gochecknoinits // generated code
func init() {
    rsa3072PrivateKey = MustParseRSAPrivateKey(rsa3072PrivateKeyPEM)
	rsa3072PublicKeyPEM = MustMarshalPublicKey(&rsa3072PrivateKey.PublicKey)
}

// GetRSA3072PrivateKey returns a known RSA3072 private key.
func GetRSA3072PrivateKey() *rsa.PrivateKey {
    return rsa3072PrivateKey
}

// GetRSA3072PublicKey returns a known RSA3072 private key.
func GetRSA3072PublicKey() *rsa.PublicKey {
    return &rsa3072PrivateKey.PublicKey
}

// GetRSA3072PublicKeyPEM returns a known RSA3072 public key in PEM format.
func GetRSA3072PublicKeyPEM() []byte {
    return rsa3072PublicKeyPEM
}
