// This file is automatically generated. DO NOT EDIT.

package testkeys_test

import (
	"testing"

	"github.com/tprasadtp/cryptokms/internal/cryptoutils"
	"github.com/tprasadtp/cryptokms/internal/testkeys"
)


func Test_Get_RSA3072(t *testing.T) {
    // Ensure Public key is returned which corresponds to Private key
    priv := testkeys.GetRSA3072PrivateKey()
    if !priv.PublicKey.Equal(testkeys.GetRSA3072PublicKey()) {
        t.Errorf("GetRSA3072PrivateKey.PublicKey != GetRSA3072PrivateKey")
    }

    // Ensure GetRSA3072PublicKey returns same key as GetRSA3072PublicKeyPEM
    pubFromPEM := cryptoutils.MustParseRSAPublicKey(testkeys.GetRSA3072PublicKeyPEM())
	if !pubFromPEM.Equal(testkeys.GetRSA3072PublicKey()) {
		t.Errorf("parse(GetRSA3072PrivateKeyPEM) != GetRSA3072PrivateKey.Public")
	}
}
