// This file is automatically generated. DO NOT EDIT.

package testkeys

import (
	"crypto/rsa"
    _ "embed"
)

//go:embed keys/rsa_1024.key
var rsa1024PrivateKeyPEM []byte

var rsa1024PublicKeyPEM []byte
var rsa1024PrivateKey *rsa.PrivateKey

//nolint:gochecknoinits // generated code
func init() {
    rsa1024PrivateKey = MustParseRSAPrivateKey(rsa1024PrivateKeyPEM)
	rsa1024PublicKeyPEM = MustMarshalPublicKey(&rsa1024PrivateKey.PublicKey)
}

// GetRSA1024PrivateKey returns a known RSA1024 private key.
func GetRSA1024PrivateKey() *rsa.PrivateKey {
    return rsa1024PrivateKey
}

// GetRSA1024PublicKey returns a known RSA1024 private key.
func GetRSA1024PublicKey() *rsa.PublicKey {
    return &rsa1024PrivateKey.PublicKey
}

// GetRSA1024PublicKeyPEM returns a known RSA1024 public key in PEM format.
func GetRSA1024PublicKeyPEM() []byte {
    return rsa1024PublicKeyPEM
}
