// SPDX-FileCopyrightText: Copyright 2023 Prasad Tengse
// SPDX-License-Identifier: MIT

package cryptokms_test

import (
	"strings"
	"testing"

	"github.com/tprasadtp/cryptokms"
)

func TestAlgorithm_String_Ensure_TrimPrefix(t *testing.T) {
	// This test is not really necessary as code is generated by stringer.
	// But this adds a check to ensure stringer strips prefix "Algorithm" from output string.
	if strings.HasPrefix(cryptokms.Algorithm(0).String(), "Algorithm") {
		t.Errorf("Stringer invalid")
	}
}
