// Code generated by "stringer -type Algorithm -trimprefix=Algorithm"; DO NOT EDIT.

package cryptokms

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlgorithmUnknown-0]
	_ = x[AlgorithmRSA2048-1]
	_ = x[AlgorithmRSA3072-2]
	_ = x[AlgorithmRSA4096-3]
	_ = x[AlgorithmRSA8192-4]
	_ = x[AlgorithmECP256-5]
	_ = x[AlgorithmECP384-6]
	_ = x[AlgorithmECP521-7]
	_ = x[AlgorithmED25519-8]
	_ = x[AlgorithmSymmetricAWS-9]
	_ = x[AlgorithmSymmetricGCP-10]
}

const _Algorithm_name = "UnknownRSA2048RSA3072RSA4096RSA8192ECP256ECP384ECP521ED25519SymmetricAWSSymmetricGCP"

var _Algorithm_index = [...]uint8{0, 7, 14, 21, 28, 35, 41, 47, 53, 60, 72, 84}

func (i Algorithm) String() string {
	if i < 0 || i >= Algorithm(len(_Algorithm_index)-1) {
		return "Algorithm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Algorithm_name[_Algorithm_index[i]:_Algorithm_index[i+1]]
}
