// Code generated by "stringer -type Backend -trimprefix=Backend"; DO NOT EDIT.

package cryptokms

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[BackendUnknown-0]
	_ = x[BackendGoogleCloudKMS-1]
	_ = x[BackendAWSKMS-2]
	_ = x[BackendHashicorpVault-3]
	_ = x[BackendAzureKeyVault-4]
	_ = x[BackendFakeKMS-5]
	_ = x[BackendFilesystem-6]
	_ = x[BackendTPM-7]
}

const _Backend_name = "UnknownGoogleCloudKMSAWSKMSHashicorpVaultAzureKeyVaultFakeKMSFilesystemTPM"

var _Backend_index = [...]uint8{0, 7, 21, 27, 41, 54, 61, 71, 74}

func (i Backend) String() string {
	if i < 0 || i >= Backend(len(_Backend_index)-1) {
		return "Backend(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Backend_name[_Backend_index[i]:_Backend_index[i+1]]
}
