package cryptokms_test

import (
	"strings"
	"testing"

	"github.com/tprasadtp/cryptokms"
)

func TestBackend_String_Ensure_TrimPrefix(t *testing.T) {
	// This test is not really necessary as code is generated by stringer.
	// But this adds a check to ensure stringer strips prefix Backend from output string.
	if strings.HasPrefix(cryptokms.Backend(0).String(), "Backend") {
		t.Errorf("Stringer invalid")
	}
}
