services:
  localstack:
    container_name: "localkms_cryptokms"
    image: nsmithuk/local-kms:latest
    ports:
      - target: 8080
        published: 8088
        protocol: tcp
    volumes:
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /data
    environment:
      KMS_REGION: us-east-1
      KMS_ACCOUNT_ID: "000000000000"
    labels:
      io.github.tprasadtp.metadata.spinner.autoclean: "true"
      io.github.tprasadtp.metadata.spinner.project: "tprasadtp/cryptokms"
