// This file is automatically generated. DO NOT EDIT.

// Package testdata includes fixtures, HTTP playback helpers
// and metadata for integration tests.
package testdata

import (
    "fmt"
    "strings"
)

// AWS Region used for generating test data.
const AWSRegion = "us-east-1"

// Key ARN is generated by server and is non-deterministic.
// Given keyType returns AWS ARN for that key. This relies on testdata.go
// as it ensures only one key of specified keySpec and key usage is generated.
// This function panics if no matching key is found.
//
// keyUsage can be
//  - SIGN_VERIFY for Singer keys
//  - ENCRYPT_DECRYPT fof Decrypter keys
//  - All other value results in panic.
//
// keySpec can be
//  - RSA_2048 (with key usage SIGN_VERIFY and ENCRYPT_DECRYPT)
//  - RSA_3072 (with key usage SIGN_VERIFY and ENCRYPT_DECRYPT)
//  - RSA_4096 (with key usage SIGN_VERIFY and ENCRYPT_DECRYPT)
//  - ECC_NIST_P256 (with key usage SIGN_VERIFY)
//  - ECC_NIST_P384 (with key usage SIGN_VERIFY)
//  - ECC_NIST_P512 (with key usage SIGN_VERIFY)
//  - any other value results in panic.
func MustGetKeyARN(keySpec, keyUsage string) string {
    switch strings.ToUpper(keyUsage) {
    case "ENCRYPT_DECRYPT":
        switch strings.ToUpper(keySpec) {
        case "RSA_2048":
            return "arn:aws:kms:us-east-1:000000000000:key/8b4d2e51-397b-4bbc-99b2-f6720c480564"
        case "RSA_3072":
            return "arn:aws:kms:us-east-1:000000000000:key/81d2b37e-ec0d-4729-8b11-eaccb742cf27"
        case "RSA_4096":
            return "arn:aws:kms:us-east-1:000000000000:key/a5c8ed96-1327-4525-a9ed-66513ce753b0"
        default:
            panic(fmt.Sprintf("unsupported keySpec=%s(%s)", keySpec, keyUsage))
        }
    case "SIGN_VERIFY":
        switch strings.ToUpper(keySpec) {
        case "ECC_NIST_P256":
            return "arn:aws:kms:us-east-1:000000000000:key/f0af276c-b794-4fc1-acda-39c4e4fccb14"
        case "ECC_NIST_P384":
            return "arn:aws:kms:us-east-1:000000000000:key/55e2ec54-fb6f-4ef9-acfa-d1537ef7d82e"
        case "ECC_NIST_P521":
            return "arn:aws:kms:us-east-1:000000000000:key/9d5d8f46-ad8a-4bb5-8016-581db7366a65"
        case "RSA_2048":
            return "arn:aws:kms:us-east-1:000000000000:key/2fd8eb4e-2ff6-495a-903c-a178d864bba3"
        case "RSA_3072":
            return "arn:aws:kms:us-east-1:000000000000:key/df961b3a-79a7-443c-a695-9bbef083d7ae"
        case "RSA_4096":
            return "arn:aws:kms:us-east-1:000000000000:key/5d99b6f0-e8ff-4aad-8ab1-c02a6f9e310f"
        default:
            panic(fmt.Sprintf("unsupported keySpec=%s(%s)", keySpec, keyUsage))
        }
    default:
        panic(fmt.Sprintf("unsupported keyUsage=%s[%s]", keyUsage, keySpec))
    }
}
