// This file is automatically generated. DO NOT EDIT.

// Package testdata includes fixtures, HTTP playback helpers
// and metadata for integration tests.
package testdata

import (
	"fmt"
	"strings"
)

// AWS Region used for generating test data.
const AWSRegion = "us-east-1"

// AWS KMS Endpoint Override.
const KMSEndpoint = "http://localhost:8088/"

// Key ARN is generated by server and is non-deterministic.
// Given keyType returns AWS ARN for that key. This relies on testdata.go
// as it ensures only one key of specified keySpec and key usage is generated.
// This function panics if no matching key is found.
//
// keyUsage can be
//   - SIGN_VERIFY for Singer keys
//   - ENCRYPT_DECRYPT fof Decrypter keys
//   - All other value results in panic.
//
// keySpec can be
//   - RSA_2048 (with key usage SIGN_VERIFY and ENCRYPT_DECRYPT)
//   - RSA_3072 (with key usage SIGN_VERIFY and ENCRYPT_DECRYPT)
//   - RSA_4096 (with key usage SIGN_VERIFY and ENCRYPT_DECRYPT)
//   - ECC_NIST_P256 (with key usage SIGN_VERIFY)
//   - ECC_NIST_P384 (with key usage SIGN_VERIFY)
//   - ECC_NIST_P512 (with key usage SIGN_VERIFY)
//   - any other value results in panic.
func MustGetKeyARN(keySpec, keyUsage string) string {
	switch strings.ToUpper(keyUsage) {
	case "ENCRYPT_DECRYPT":
		switch strings.ToUpper(keySpec) {
		case "RSA_2048":
			return "arn:aws:kms:us-east-1:000000000000:key/891b5194-8f37-4a31-820f-8784e913be99"
		case "RSA_3072":
			return "arn:aws:kms:us-east-1:000000000000:key/e9205d5b-0870-4832-8bd1-707b16ca4857"
		case "RSA_4096":
			return "arn:aws:kms:us-east-1:000000000000:key/563e26bd-626a-4999-bd3d-e01d8246fdb7"
		default:
			panic(fmt.Sprintf("unsupported keySpec=%s(%s)", keySpec, keyUsage))
		}
	case "SIGN_VERIFY":
		switch strings.ToUpper(keySpec) {
		case "ECC_NIST_P256":
			return "arn:aws:kms:us-east-1:000000000000:key/4b4734b0-d248-481d-85a1-8791bb8d8ade"
		case "ECC_NIST_P384":
			return "arn:aws:kms:us-east-1:000000000000:key/a5dc6661-e171-4bd1-ab4e-0c65c0d8b16b"
		case "ECC_NIST_P521":
			return "arn:aws:kms:us-east-1:000000000000:key/77d0a400-577e-409c-9739-a584793d9db6"
		case "RSA_2048":
			return "arn:aws:kms:us-east-1:000000000000:key/da9b5630-82f4-4390-b4da-75fb955c2a80"
		case "RSA_3072":
			return "arn:aws:kms:us-east-1:000000000000:key/f17321e0-33d5-46d8-807a-6033642c19e4"
		case "RSA_4096":
			return "arn:aws:kms:us-east-1:000000000000:key/d0e362d7-f144-4d8d-b4c0-2496f6c4e0a0"
		default:
			panic(fmt.Sprintf("unsupported keySpec=%s(%s)", keySpec, keyUsage))
		}
	default:
		panic(fmt.Sprintf("unsupported keyUsage=%s[%s]", keyUsage, keySpec))
	}
}
